### ISSUE TITLE
Project Milestones

### ISSUE THREAD

**Issue by isha-11** [isha-11/wordle#1]
Tooling:
- [ ] PlantUML - HLD diagram
- [x] Vitejs
- [x] Testing, code coverage, TDD
- [x] Github actions - build, test, deploy
- [x] Prettier
- [x] Eslint
- [ ] Web Analytics

Functional implementations:
- [ ] React 18
- [x] Babel plugins - preval, styled-components
- [ ] Data Persistor
- [ ] Service Worker - PWA
- [ ] SSG
- [ ] Web Worker
- [x] Web Vibration API
- [x] Web Animations API
- [ ] Web Storage API - sessionStorage
- [ ] Theme - System preferred, dark, light
- [ ] Web Crypto API

Tasks:
- [x] Keyboard sync with the game
- [ ] CSS
  - [x] Styled-components setup
  - [x] Keyboard Wordboard styling
  - [ ] Responsive
- [ ] Won and Lost Prompt
- [x] Refactor
- [x] babel-plugin-styled-components
- [x] Update dependencies with node-check-updates
- [ ] Dictionary setup and implementation
- [ ] HTML meta tags
- [ ] useSyncState library
- [x] License and license badge
- [x] Setup husky and lint-staged
- [x] Consolidate commands in workflow.yml
- [x] Wordboard Letter type - Animation
- [ ] Accessibility
- [ ] Fat fingers
- [x] Keypress effect
  - [x] Animation
  - [x] Audio - Explored, decided not to implement
  - [x] Vibration
- [ ] Persistor
  - [x] createSessionReducer hook factory
  - [ ] Wordle reducer
  - [x] useInitialState hook
  - [ ] Persistor-Game integration
